[buildPlans.CaskeyNarrow]
family = "Caskey Narrow"
spacing = "term"
serifs = "sans"

[buildPlans.CaskeyNarrow.widths.Normal]
shape = 550
menu = 5
css = "normal"

[buildPlans.CaskeyNarrow.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.CaskeyNarrow.weights.Bold]
shape = 600
menu = 700
css = 700

[buildPlans.CaskeyNarrow.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.CaskeyNarrow.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
